name: Update Version on Repository Dispatch

on:
  repository_dispatch:
    types:
      - update-version

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Update Version
      run: |
        echo "github.event.client_payload.version = ${{ github.event.client_payload.version }}"
