name: pr-trigger

on:
  pull_request:
    types:
      - labeled


jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test-workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          script: |
            console.log(context);
            try {
              const ref = context.ref;
              const response = await github.rest.actions.createWorkflowDispatch({
                owner: 'RahulKumar1606',
                repo: 'test-repo',
                workflow_id: 'test-workflow.yml',
                ref: ref
              });
              console.log('Workflow dispatch triggered:', response.status);
            } catch (error) {
              console.error('Error triggering workflow dispatch:', error.message);
            }