name: pr-trigger

on:
  pull_request:
    types:
      - labeled


jobs:
#  check-if-we-can-run:
#    runs-on: ubuntu-latest
#    if: ${{github.event.action == 'labeled' && github.event.label.name == 'ci'}}
#    steps:
#      - name: Run on label
#        run: |
#          echo "Completed"
  workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test-workflow
        id: trigger-test-workflow
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          repo: RahulKumar1606/test-repo
          ref: ${{ github.event.pull_request.head.ref }}
          workflow: test-workflow.yml
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          wait-for-completion: true
          display-workflow-run-url: true

      - name: Get Workflow Run ID
        id: extract-id
        run: |
          # Extract the run ID from the workflow URL
          workflow_url="${{ steps.trigger-test-workflow.outputs.workflow_run_url }}"
          run_id=$(echo "$workflow_url" | awk -F'/' '{print $(NF)}')
          echo "::set-output name=run_id::$run_id"

      - name: Fetch Logs using Workflow Run ID
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = "${{ steps.extract-id.outputs.run_id }}";
            const response = await github.actions.getWorkflowRunLogs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            console.log(response.data);
