name: pr-trigger

on:
  pull_request:
    types:
      - labeled


jobs:
#  check-if-we-can-run:
#    runs-on: ubuntu-latest
#    if: ${{github.event.action == 'labeled' && github.event.label.name == 'ci'}}
#    steps:
#      - name: Run on label
#        run: |
#          echo "Completed"
  workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test-workflow
        id: trigger-test-workflow
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          repo: RahulKumar1606/test-repo
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          workflow: test-workflow.yml
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          wait-for-completion: true
          wait-for-completion-interval: 10s
          display-workflow-run-url: true
