name: Preflight

on:
  pull_request:
    types:
      - labeled

jobs:
  check-if-we-can-run:
    runs-on: ubuntu-latest
    if: ${{github.event.action == 'labeled' && github.event.label.name == 'ci'}}
    steps:
      - name: Run on label
        run: |
          echo "Completed"

