name: Test Workflow

on:
  workflow_run:
    workflows:
      - pr-trigger
    types:
      - completed
  pull_request:
    branches:
      - main


jobs:
  failing-job:
    if: ${{ github.event_name == 'workflow_run' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deliberatly failing
        run: abcdef

  build-image:
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: check if trigger by label
        run: |
          echo ${{github.event.action}}
          echo ${{github.event.label.name}}
