name: Test Workflow

on:
  repository_dispatch:
    types: [ test ]
  workflow_dispatch:
  pull_request:


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: check if trigger by label
        run: |
          echo "Hello world"
          echo ${{github.event.action}}
          echo ${{github.event.label.name}}