name: Update Version on Repository Dispatch

# on:
#   repository_dispatch:
#     types:
#       - update-version
on:
  push:
    branches:
      - "main"

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update Version
      run: |
        echo "github.event.client_payload.version = ${{ github.event.client_payload.version }}"
